### ISSUE TITLE
Add authentication to Docker Hub on CircleCI

### ISSUE THREAD

**Issue by fortoulrodolfo** [Medology/laravel-sodium#14]
@fortoulrodolfo commented on [Tue Oct 06 2020](https://github.com/Medology/medivo-client/issues/66)

# Description
On November 1st, Docker Hub will begin limiting anonymous image pulls. We might be impacted and should make the proper changes to avoid interruptions to our workflow.

Adding Docker authentication to our pipeline config is the easiest way to avoid any service disruptions because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.

- [Rate Limit](https://docs.docker.com/docker-hub/download-rate-limit/?mkt_tok=eyJpIjoiTWpVek5EQTVOMkppTXpWaCIsInQiOiJMMTAxZkpmTXJpYm9NVVwvZERsb1Vub0RjNitTY3I2YUhvWGtYUGp0d05scEVYUkY2djdoS1h2b1g1aW5DaDJjTEZiUG1DaFNwWk1LdHpiZkpqWVFnaXo5WHN4WWV2NWFjcGQrNGFmZVF1M2NWYUpEWnBWaXNnWStKWE5ETGR0blIifQ%3D%3D)

## Negative Impact:
We might be impacted by the limit on pulling images anonymously and our CI builds could fail.

# Proposed Solution:
Add Docker authentication to our config will avoid service disruptions.

## How will the proposed solution address the negative impact(s)?
According to Docker authenticated users get higher per-user rate limits.

## Side Effects
We have a deadline on Nov 1st to add auth to our Docker process or we may get our CI builds fail

## QA Needs
Verifying that pulling images in CI is working as before.

## Acceptance Criteria
- [ ] Add [Docker Authentication](https://circleci.com/docs/2.0/private-images/?mkt_tok=eyJpIjoiTWpVek5EQTVOMkppTXpWaCIsInQiOiJMMTAxZkpmTXJpYm9NVVwvZERsb1Vub0RjNitTY3I2YUhvWGtYUGp0d05scEVYUkY2djdoS1h2b1g1aW5DaDJjTEZiUG1DaFNwWk1LdHpiZkpqWVFnaXo5WHN4WWV2NWFjcGQrNGFmZVF1M2NWYUpEWnBWaXNnWStKWE5ETGR0blIifQ%3D%3D) to our CI config 

## Announcement Message
releasenotes: < if the Issue is something visible to the end user, then put the text for the releasenotes slack channel here. Otherwise indicate "N/A" >

devchat: < If HL Engineering requires notification instead of the end user or if there is different information, then put the text here. Otherwise indicate "N/A" >

### Ready for Planning
- [X] Story and Business Value complete
- [X] Initial Acceptance Criteria Defined
- [X] The person who will Approve story identified
- [X] Proposed Solution provided

### Ready for Review
- [ ] Testing implemented and passed

### Ready for Pre-Production QA
- [ ] Issue scored
- [ ] Special testing instructions noted
- [ ] Acceptance criteria met - boxes checked
- [ ] Announcement message created

### Ready for SM Approval
- [ ] Acceptance Test Results included in Comment

### Ready for PO Approval
- [ ] Announcement message approved
- [ ] Issue complete and correct in all required sections
- [ ] All checkboxes checked

**Comment by DevanTarunKumar** [comment]
scored with @Chekote and @PayneWheat
