### ISSUE TITLE
Repo permission issues.

### ISSUE THREAD

**Issue by BKorenek** [Medology/laravel-sodium#7]
Developers have the ability to force merge into master of the laravel-sodium. The permissions for this repo should be the same as all repos.

**Comment by BKorenek** [comment]
Also no approver labels in repo.

**Comment by BKorenek** [comment]
No time today, will look into it tomorrow.

**Comment by Chekote** [comment]
I audited all the repos and ensured that each one has branch protection enabled for master.

**Comment by Chekote** [comment]
It's trivial to add new labels as they are needed. I don't think it's a good use of time to go through all the repos and add labels just in case we might need them.

**Comment by Chekote** [comment]
Scored with @BKorenek and @manuerumx
